# -*- coding: utf-8 -*-
"""Assignment1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1oWqEyTSJB6atHxXRVSRr3cFeUWt3rEiZ
"""

#***************LIST****************
lst = ["Nandhu", 22, "Coimbatore"]
#lst
lst.append(1998)
#lst
lst.index(22)
lst.reverse()
#lst
lst.count(1998)
lst.remove(22)
lst

#****************Dictionary****************
dict = {'Name': 'Nandhu', 'Age': 22, 'Place': 'Coimbatore'}
#dict
dict.keys()
dict.items()
dict.values()
dict.get('Name')
dict.clear()
dict

#**************************Sets***************
set={'BMW', 'Audi', 'TaTa', 'Benz'}
#set
set.add('Toyota')
#set
set.update(['KIYA'])
#set
len(set)
set.remove('KIYA')
#set
set.discard('TaTa')
set

#******************Tuple********************
tup1 = ('Nandhu', 22, 'Coimbatore')
#tup1
len(tup1)
tup1[2]
tup2 = ('Chennai', 21)
tup3 = tup2 + tup1
tup3
del tup2
tup1[0:2]

#*****************Strings*********************
str = 'I Love India'
#str
str[5]
str[2:12]
str1 = str[:7] + 'Python'
str1.capitalize()
len(str)
str.swapcase()
